<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'MBtec\Cache\Service\CacheFactory' => __DIR__ . '/src/Service/CacheFactory.php',
    'MBtec\Cache\Module' => __DIR__ . '/Module.php',
);
