<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'MBtecZfCache\Service\CacheFactory' => __DIR__ . '/src/Service/CacheFactory.php',
    'MBtecZfCache\Module' => __DIR__ . '/Module.php',
);
